### ISSUE TITLE
Add Epic Stack Project

### ISSUE THREAD

**Issue by BBlackwo** [michaelrambeau/bestofjs#759]
**Please briefly describe the project you'd like to add to _Best of JS_?**

This is a Full Stack app starter with the foundational things setup and configured for you to hit the ground running on your next EPIC idea.

**What is the URL of the project you'd like to add to _Best of JS_?**

https://github.com/epicweb-dev/epic-stack

**Before submitting the request to add a new project, please check the following points:**

- [X] The project is related to the web platform or Node.js
- [X] The project has more than 100 stars on GitHub
- [X] The project has thorough documentation in English
- [X] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

React, Remix, Boilerplate. 

Maybe Tailwind too?

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

**Comment by michaelrambeau** [comment]
Thank you Benjamin @BBlackwo `Epic Stack` is available on _Best of JS_, please check:

https://beta.bestofjs.org/projects/epic-stack

I don't think there is a package on NPM (to be able to show the monthly downloads), unless I missed something?

**Comment by BBlackwo** [comment]
Great, thanks Michael @michaelrambeau.

That's correct, no NPM package that I'm aware of.
