### ISSUE TITLE
Add VANILLA TODO

### ISSUE THREAD

**Issue by morris** [michaelrambeau/bestofjs#987]
**Please briefly describe the project you'd like to add to _Best of JS_?**

VANILLA TODO is a case study on viable techniques for vanilla web development. By building a TeuxDeux clone in plain HTML, CSS, and JS, the study demonstrates that vanilla web development can be viable in terms of maintainability, and worthwhile in terms of user experience (50% less time to load and 95% less bandwidth in this case).

**What is the GitHub repository of the project you'd like to add to _Best of JS_?**

https://github.com/morris/vanilla-todo

**Before submitting the request to add a new project, please check the following points:**

- [x] The project is related to the web platform or Node.js
- [x] The source code is on GitHub and project has more than 100 stars on GitHub
- [x] The project has thorough documentation in English
- [x] The project is not deprecated and actively maintained

**How would this project be tagged? (Pick one or several existing tags from this list: https://bestofjs.org/tags)**

Performance

**Also you can suggest new tags to add if you think _Best of JS_ is missing useful tags.**

Patterns, vanilla

**Comment by michaelrambeau** [comment]
Hello @morris thank you for the recommendation, `Vanilla TODO` is available on _Best of JS_, please check:

https://bestofjs.org/projects/vanilla-todo

**Comment by morris** [comment]
Thanks a lot!
